apiVersion: v1
kind: Pod
metadata: 
   name: guestbook-app-pod
   labels:
     name: guestbook-app-pod
     app: demo-guestbook-app
spec:
   containers:
     - name: guestbook-app
       image: kubernetes/guestbook:v2
       ports:
         - containerPort: 80
